eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: service-one
        uri: http://localhost:9091/
        predicates:
        - Path=/project/**
#      - id: secondModule
#        uri: http://localhost:8082/
#        predicates:
#        - Path=/service2/**